baseurl = "https://comunidades.dev"
title = "Comunidades Dev"
theme = "bootstrap-clean"
removePathAccents = true

[taxonomies]
tag = "tags"
formato = "formatos"
tema = "temas"


[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    author = "Software Guru"
    favicon = "favicon.ico"
    description = "Directorio de comunidades de tecnología en Latam"

[outputs]
    section = ["JSON", "HTML", "RSS"]
    taxonomy = ["JSON", "HTML", "RSS"]
    term = ["JSON", "HTML", "RSS"]

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

[[menu.main]]
    name = "Comunidades"
    url = "/comunidades"
    weight = 2

[[menu.main]]
    name = "Temas"
    url = "/temas"
    weight = 4

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 5


[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"

[[params.plugins.css]]
link = "https://unpkg.com/bootstrap-table@1.21.0/dist/bootstrap-table.min.css"

# JS Plugins

[[params.plugins.js]]
link = "https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"

[[params.plugins.js]]
link="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"

[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.21.0/dist/bootstrap-table.min.js"
